//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pol_Party_courseEntities : DbContext
    {
        public Pol_Party_courseEntities()
            : base("name=Pol_Party_courseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Обращение> Обращение { get; set; }
        public virtual DbSet<Отделение> Отделение { get; set; }
        public virtual DbSet<Проект> Проект { get; set; }
        public virtual DbSet<Событие> Событие { get; set; }
        public virtual DbSet<Член_Партии> Член_Партии { get; set; }
    }
}
