//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Обращение
    {
        public int Идентификатор_Обращения { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<bool> Пол { get; set; }
        public string Текст { get; set; }
        public string Телефон { get; set; }
        public string Электронная_Почта { get; set; }
        public int Идентификатор_Отделения { get; set; }
    
        public virtual Отделение Отделение { get; set; }
    }
}
