//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отделение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отделение()
        {
            this.Обращение = new HashSet<Обращение>();
            this.Проект = new HashSet<Проект>();
        }
    
        public int Идентификатор_Отделения { get; set; }
        public int Номер_Региона { get; set; }
        public string Адрес { get; set; }
        public string Сайт { get; set; }
        public string Телефон { get; set; }
        public int Идентификатор_Члена_Партии { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Обращение> Обращение { get; set; }
        public virtual Член_Партии Член_Партии { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проект> Проект { get; set; }
    }
}
