//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проект
    {
        public int Идентификатор_Проекта { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public decimal Финансирование { get; set; }
        public int Идентификаторы_Члена_Партии { get; set; }
        public int Идентификатор_Отделения { get; set; }
    
        public virtual Отделение Отделение { get; set; }
        public virtual Член_Партии Член_Партии { get; set; }
    }
}
