//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Событие
    {
        public int Идентификатор_События { get; set; }
        public System.DateTime Дата_Проведения { get; set; }
        public string Описание { get; set; }
        public int Идентификатор_Члена_Партии { get; set; }
    
        public virtual Член_Партии Член_Партии { get; set; }
    }
}
