//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coursedb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Член_Партии
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Член_Партии()
        {
            this.Отделение = new HashSet<Отделение>();
            this.Проект = new HashSet<Проект>();
            this.Событие = new HashSet<Событие>();
        }
    
        public int Идентификатор_Члена_Партии { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public Nullable<bool> Пол { get; set; }
        public Nullable<System.DateTime> Дата_Рождения { get; set; }
        public string Телефон { get; set; }
        public string Электронная_Почта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отделение> Отделение { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проект> Проект { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Событие> Событие { get; set; }
    }
}
